server:
  port: 8888

shoppo:
  stat:
    cron : "${CRON_STAT: */20 * * * * *}"
    zone : "Europe/Paris"

mongo:
  database :
    url: "mongodb://${MONGO_HOST:127.0.0.1}:${MONGO_PORT:27017}/"
    name : "stat"

spring:
  rabbitmq:
    host: ${RABBIT_HOST:172.28.100.26}
    port: ${RABBIT_PORT:5676}
    username: ${RABBIT_USERNAME:shoppo}
    password: ${RABBIT_PASSWORD:shoppo2020}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${PG_HOST:172.28.100.26}:${PG_PORT:5432}/${PG_DB:shoppoDev}
    username: ${PG_USER:shoppo}
    password: ${PG_PASSWORD:shoppo2020}
    hikari:
      maximum-pool-size: 1
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false


mq:
  x-message-ttl: 5000
  exchange:
    stat: "exchange_stat"
  queue:
    stat:
      create-commande: "queue_stat_create_commande"
      read: "queue_stat_read"
  routing-key:
    create-commande: "stat_create_commande"
    read: "stat_read"
